"""netmon/relay.py -- generate a per-machine bettercap caplet.

Whole-network mode needs bettercap to ARP-spoof the LAN, and bettercap
needs the *exact* interface name for the machine it runs on. On Windows
that is a \\Device\\NPF_{GUID} string that is different on every PC, so a
checked-in caplet can never work everywhere. This module detects the right
interface and subnet on *this* machine and writes a personalized caplet.

Usage:
    python -m netmon.relay          # show what would be generated
    python -m netmon.relay --write  # write netmon/wifimon.local.cap

The generated file is git-ignored (it contains this machine's interface
GUID). The checked-in netmon/wifimon.cap stays as the documented template.
"""

import argparse
import ipaddress
import socket
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TEMPLATE = HERE / "wifimon.cap"
GENERATED = HERE / "wifimon.local.cap"

CAPLET_TEMPLATE = """\
# Generated by `python -m netmon.relay --write` on this machine.
# Do not commit this file -- it names this PC's network interface.
#
# WHAT IT DOES: ARP-spoofs your own LAN ({targets}) so this machine
# relays traffic between your devices and the router. Orion, sniffing
# the Wi-Fi interface, then sees every device's conversations.
#
# ONLY run this on a network you own. While it runs, this machine is the
# LAN's man in the middle: if it sleeps, reboots, or bettercap dies, the
# other devices lose internet until their ARP tables recover (< 1 min).
#
# RUN (as Administrator on Windows, root elsewhere):
#   {run_cmd}
# STOP: type `quit` in the bettercap console (it restores ARP on exit).

set arp.spoof.fullduplex true
set arp.spoof.targets {targets}
arp.spoof on
"""


def _default_ip():
    """This machine's primary LAN IP (no traffic sent)."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return None


def detect_relay_target():
    """Return (bettercap_iface, subnet_cidr) for this machine.

    bettercap_iface is the \\Device\\NPF_{GUID} string on Windows, the
    plain interface name (wlan0, en0, ...) elsewhere. Falls back to
    scapy's default sniff interface when the GUID lookup fails.
    Never raises: returns (None, None) when nothing can be determined.
    """
    ip = _default_ip()
    subnet = None
    if ip:
        try:
            # Most home/SMB LANs are /24; derive from our own address.
            subnet = str(ipaddress.ip_network(ip + "/24", strict=False))
        except ValueError:
            pass
    iface = None
    try:
        from scapy.all import conf  # optional dependency
        if sys.platform == "win32":
            try:
                from scapy.arch.windows import get_windows_if_list
                for entry in get_windows_if_list():
                    name = entry.get("name", "")
                    if name.startswith(r"\Device\NPF_"):
                        # Prefer the interface whose IP matches ours.
                        ips = entry.get("ips", []) or []
                        if ip and any(ip in str(x) for x in ips):
                            iface = name
                            break
                        if iface is None:
                            iface = name
            except Exception:
                pass
        if iface is None:
            # conf.iface is what sniff() would use by default.
            iface = str(getattr(conf, "iface", "") or "") or None
    except Exception:
        pass
    return iface, subnet


def write_caplet(path=None):
    """Write the personalized caplet. Returns the path, or raises."""
    iface, subnet = detect_relay_target()
    if not iface or not subnet:
        raise RuntimeError(
            "could not determine this machine's interface/subnet;"
            " connect to the LAN first, then retry.")
    path = Path(path or GENERATED)
    if sys.platform == "win32":
        run_cmd = (f'bettercap.exe -iface "{iface}"'
                   f' -caplet "{path}"')
    else:
        run_cmd = f"sudo bettercap -iface {iface} -caplet {path}"
    path.write_text(CAPLET_TEMPLATE.format(
        targets=subnet, run_cmd=run_cmd))
    return path, iface, subnet, run_cmd


def main():
    ap = argparse.ArgumentParser(
        description="Generate a per-machine bettercap relay caplet.")
    ap.add_argument("--write", action="store_true",
                    help="write netmon/wifimon.local.cap")
    args = ap.parse_args()
    if args.write:
        try:
            path, iface, subnet, run_cmd = write_caplet()
        except RuntimeError as exc:
            print(f"relay: ERROR: {exc}", file=sys.stderr)
            sys.exit(1)
        print(f"relay: wrote {path}")
        print(f"relay: interface {iface}")
        print(f"relay: targets    {subnet}")
        print()
        print("Run as Administrator/root:")
        print(f"  {run_cmd}")
        print("Stop by typing: quit")
    else:
        iface, subnet = detect_relay_target()
        print(f"interface: {iface or '(could not detect -- connect to LAN)'}")
        print(f"subnet:    {subnet or '(could not detect)'}")
        print("Run with --write to generate the caplet.")


if __name__ == "__main__":
    main()
